services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models/checkpoints:/app/models/checkpoints
      - ./output:/app/output
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DOWNLOAD_MODEL=true
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
